; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:waveshare-esp32s3-touch-lcd-3_5]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; 16MB Flash, 8MB PSRAM (OPI)
board_build.flash_size = 16MB
board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi

; 460800 default is flaky on this board's USB-Serial/JTAG — pin to 115200
upload_speed = 115200
monitor_speed = 115200
monitor_filters = send_on_enter
monitor_eol = LF

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_BOOT_INIT
    ; LCD resolution
    -DLCD_WIDTH=480
    -DLCD_HEIGHT=320

lib_deps =
    nrf24/RF24
    moononournation/GFX Library for Arduino @ 1.5.5
    robtillaart/TCA9554 @ ^0.1.3
    lewisxhe/XPowersLib @ ^0.2.4
